# Generated by Django 6.0.1 on 2026-07-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Componente')),
                ('clasificacion', models.CharField(choices=[('SIM_AVANZADA', 'Simulación Avanzada'), ('AUDIO_INMERSIVO', 'Audio Inmersivo'), ('MOBILIARIO_PRO', 'Mobiliario Pro')], default='SIM_AVANZADA', max_length=50, verbose_name='SKU / Clasificación')),
                ('costo_comercial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Comercial ($ MXN)')),
                ('especificaciones_tecnicas', models.TextField(blank=True, null=True, verbose_name='Especificaciones Técnicas')),
                ('existencia_inicial', models.PositiveIntegerField(default=0, verbose_name='Existencia Inicial Almacén')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-create'],
            },
        ),
    ]
