# Generated by Django 6.0.1 on 2026-07-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_orden_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
