# Generated by Django 6.0.1 on 2026-07-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_producto_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
