# Generated by Django 6.0.5 on 2026-07-12 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinión',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150, verbose_name='Usuario')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('response', models.TextField(blank=True, null=True, verbose_name='Respuesta')),
                ('is_hidden', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Opinión',
                'verbose_name_plural': 'Opiniones',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('direccion_postal', models.CharField(max_length=255, verbose_name='Dirección Postal')),
                ('estado_ciudad', models.CharField(max_length=150, verbose_name='Estado / Ciudad')),
                ('codigo_postal', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('metodo_pago', models.CharField(choices=[('TARJETA', 'Tarjeta de Crédito / Débito'), ('PAYPAL', 'PayPal System')], default='TARJETA', max_length=20)),
                ('total_neto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Neto a Pagar')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-created'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='create',
            new_name='created',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos', verbose_name='Fotografía'),
        ),
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='game.orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.producto')),
            ],
        ),
    ]
