# Generated by Django 6.0.5 on 2026-07-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_opinión_orden_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={'ordering': ['-created'], 'verbose_name': 'Orden', 'verbose_name_plural': 'Ordenes'},
        ),
        migrations.AlterField(
            model_name='opinión',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
