# Generated by Django 6.0.1 on 2026-07-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_orden_options_alter_opinión_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinión',
            name='is_hidden',
            field=models.BooleanField(default=True),
        ),
    ]
