# Generated by Django 6.0.1 on 2026-07-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_opinión_is_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinión',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='opinión',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='Aprobado', max_length=20),
        ),
    ]
