# Generated by Django 6.0.1 on 2026-07-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_opinión_is_hidden_alter_opinión_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinión',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='APROBADO', max_length=20),
        ),
    ]
