# Generated by Django 6.0.1 on 2026-07-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_opinión_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('password', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Es Administrador')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
