# Generated by Django 6.0.1 on 2026-08-14 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_orden_usuario_alter_opinión_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=255, verbose_name='Calle')),
                ('numero_exterior', models.CharField(max_length=20, verbose_name='Número Exterior')),
                ('numero_interior', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número Interior')),
                ('colonia', models.CharField(max_length=150, verbose_name='Colonia / Fraccionamiento')),
                ('codigo_postal', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('ciudad', models.CharField(max_length=150, verbose_name='Ciudad / Municipio')),
                ('pais', models.CharField(default='México', max_length=100, verbose_name='País')),
                ('numero_telefonico', models.CharField(max_length=20, verbose_name='Número Telefónico')),
                ('referencias', models.TextField(blank=True, null=True, verbose_name='Referencias')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='game.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'ordering': ['-created'],
            },
        ),
    ]
