# Generated by Django 6.0.5 on 2026-08-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_producto_discount_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Duda',
                'verbose_name_plural': 'Dudas',
                'ordering': ['-created'],
            },
        ),
    ]
