# Generated by Django 6.0.1 on 2026-08-19 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_duda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='game.usuario', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos', verbose_name='Fotografía'),
        ),
    ]
